#!/bin/sh
# remaps windows key to left click, Alt Gr again to left click
# some key that was already right mouse click again to right mouse click
# the keycodes can be different on each computer, find out with xev.

resume()
{
    date >> /tmp/remap
    echo "resume in 99" >> /tmp/remap
    su - burak -c /home/burak/kod/startup.sh
}
suspend()
{
    date >> /tmp/remap
    echo "suspend in 99" >> /tmp/remap
}

case "$1" in
	hibernate|suspend) suspend ;;
	thaw|resume) resume ;;
esac

