#!/bin/sh
# remaps windows key to left click, Alt Gr again to left click
# some key that was already right mouse click again to right mouse click
# the keycodes can be different on each computer, find out with xev.

resume()
{
    echo "in 99" >> /tmp/remap
    su - burak -c /bin/sh /home/burak/kod/startup.sh
}

case "$1" in
	thaw|resume) resume ;;
esac

