#!/bin/sh
# remaps windows key to left click, Alt Gr again to left click
# some key that was already right mouse click again to right mouse click
# the keycodes can be different on each computer, find out with xev.
case "$1" in
        thaw|resume)
                DISPLAY=:0.0 ; export DISPLAY 
                su - burak -c /home/burak/kod/remap_mouse.sh
                ;;
esac

